### ISSUE TITLE
t66y好像部分未生效？

### ISSUE THREAD

**Issue by Z-fly** [francis-zhao/userstyles#4]
![image](https://user-images.githubusercontent.com/10470892/105570980-792ea400-5d87-11eb-9739-8dd5013a11b9.png)
https://t66y.com/htm_data/2101/7/4301765.html

**Comment by Z-fly** [comment]
@francis-zhao

**Comment by bamf2077** [comment]
这个网站你自己添加一下强制覆盖规则吧……

```css
@-moz-document domain("t66y.com") {
  * {
    font-family: "Source Han Sans SC", "Noto Sans CJK SC", "HanHei SC", "方正兰亭黑_GB18030", "方正兰亭黑_GBK", system-ui, -apple-system, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji", emoji;
  }

  button,
  input,
  keygen,
  optgroup,
  select,
  textarea {
    font-family: inherit;
  }
  
  code,
  kbd,
  pre,
  samp {
    font-family: "Source Han Mono SC", "Noto Sans Mono CJK SC", "Source Code Pro", "Noto Mono", "Roboto Mono", "Source Han Sans SC", "Noto Sans CJK SC", "HanHei SC", "方正兰亭黑_GB18030", "方正兰亭黑_GBK", system-ui, -apple-system, monospace, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji", emoji;
  }
}

```
