### ISSUE TITLE
自己加上一行感觉显示效果好些😁

### ISSUE THREAD

**Issue by weavers1f** [francis-zhao/userstyles#8]
一直自用以下样式：

```css
* {
  -webkit-text-stroke-width: 0.16px;
  text-shadow: 0.01em 0.01em 0.01em #707070;
}

/* 使修改字体不会应用于部分特殊字符符号和图标以及按钮等网页元素,完美解决字符集不全导致图标,按钮变方块的问题.*/
:not([class*='icon']):not([class*='button']):not([class*='mjx']):not([class*='fa']):not([class*='info']):not(i) {
  /* 字体设置,可分别设置中英文,前面英文字体,后面中文字体可选（需要先安装对应字体）：
     HarmonyOS Sans SC、HYQIHEI 55S、冬青黑体简体中文 W3、阿里巴巴普惠体 2.0 55 Regular、
     更纱黑体 UI SC、苹方黑体、微软雅黑、PingFang SC Regular、PingFang SC Heavy、
     Hiragino Sans GB、OppoSans、苹方-简、小米兰亭 pro vf、XHei Intel、ping hei、思源黑体 CN */
  font-family: 'HarmonyOS Sans SC' !important;
}

```

但是有个问题是打印网页为PDF的时候会字体特别粗没法看（主要是第一行代码的锅），图标有些也会变成方格（样式代码的锅）。后来还是用了这大佬你这个全局微软雅黑的样式。

不过因为1080P屏幕的原因，在EDGE或CHROME中显示效果不是很好，就将 `* { text-shadow: 0.01em 0.01em 0.01em #707070 }` 加在了全局微软雅黑的第一行，显示会稍微没那么虚。对比：

![WPS图片拼图](https://user-images.githubusercontent.com/19663899/127827563-f07a8459-a699-481c-81a8-f6c9ae08f108.png)

**Comment by weavers1f** [comment]
上面评论发出来的代码里星号变成实心黑点了

**Comment by bamf2077** [comment]
不好意思，才看到你的消息哈哈哈哈，研究了一下你的提议，但是因为每个网站的样式不一定都写的很标准，用 `-webkit-text-stroke-width` 属性很可能造成一些异常，而且很多标题并不一定是深色， `text-shadow` 属性固定深色阴影会造成浅色字体有黑边阴影，我这个样式表的目的是尽量不会对网页原有设计做影响和干扰，并没有强制替换，毕竟网站有自己的设计风格，很可能需要用一些特殊字体表现效果。

至于你说的打印问题，你可以尝试使用 CSS 媒体查询属性，把你原有的代码包进去就好了：

```css
:not([class*='icon']):not([class*='button']):not([class*='mjx']):not([class*='fa']):not([class*='info']):not(i) {
  font-family: 'HarmonyOS Sans SC', 'PingFang SC', '苹方-简',
    'Source Han Sans SC', 'Source Han Sans CN', '思源黑体', system-ui,
    -apple-system, ui-sans-serif, sans-serif !important;
}

/* 只对非打印页面生效的代码，日常使用 */
@media not print {
  * {
    -webkit-text-stroke-width: 0.16px;
    text-shadow: 0.01em 0.01em 0.01em #707070;
  }
}

/* 只对打印页面生效的代码，Ctrl + P 打印时生效 */
@media print {
  /* 打印样式 */
}
```

而且你可以单独写一个全局生效的样式表，把你自己的代码放进去，不用直接修改我的样式表，因为每次自动更新会覆盖掉你的修改，你还得手动添加。

BTW，看到你正在使用的是鸿蒙黑体，新出了一个[全局鸿蒙黑体](https://greasyfork.org/zh-CN/scripts/439505)，有兴趣可以尝试一下。
